name: AntiHealthIndicator
author: LaserSlime
description: Filters server packets to hide information such as health and saturation which can't normally be seen in vanilla.
main: me.lasersli.antihealthindicator.AntiHealthIndicator
version: 1.4.4
api-version: 1.21.10
depend: [ProtocolLib]
folia-supported: true