name: AntiHealthIndicator
author: LaserSlime
description: Filters server packets to hide information such as health and saturation which can't normally be seen in vanilla.
<<<<<<< HEAD
main: me.lasersli.antihealthindicator.AntiHealthIndicator
version: 1.4.3
api-version: 1.21.3
depend: [ProtocolLib]
folia-supported: true